algorithm: unsup
dataset: cifar10
loss: simclr # Supcon&Simclr #OnlySupcon                        #all_withoutsimclr #all_withoutsimclr_withoutunsupce # all #only_unsup (for pretraining, and resume = True)
use_cat: True # if false allows to detach
save_dir: ./saved_models/pretrained
save_name: simclr_test_2epochs
wandb_name:
resume: False
droprate: 0
resume_only_weight: False # When resuming a model, only take the weight for finetuning (make epochs,scheduler, optimizer start from scratch)
load_path: ./saved_models/pretrained/pretrainedSimCLRcifar100wrn_28_2_epochs256/epoch124.pth #latest_model.pth epoch124
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 2 #256 #1024
num_train_iter: 100 #262144 # 1048576
num_eval_iter: 5120
num_log_iter: 256
num_labels: 10 # 100 2500cifar100
batch_size: 4 # 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.7 # 0.7 ou .95 pour fixmatchtau for pseudo labeling
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: True
clip: 0.0
net: wrn_28_2_proto
net_from_name: False # If True, net_builder takes models in torch.vision models (False de base)
data_dir: ./data
train_sampler: RandomSampler
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None



