# G pretrained backbone A resnet50
# G1 fixmatch resnet50 pretrained +resset50cifar!
# fixmatch classique
wandb_project: G
save_name: G1-500k
use_pretrain: True
pretrain_path: moco_v2_800ep_pretrain.pth
algorithm: fixmatch
dataset: cifar100
use_cat: True # if false allows to detach
save_dir: ./saved_models/classic_cv
resume: True
droprate: 0
load_path: auto #latest_model.pth epoch124
overwrite: True
use_tensorboard: True
use_wandb: True
epoch: 512 #1024 # 256
num_train_iter: 524288 # 1048576 # 262144
num_eval_iter: 5120
num_log_iter: 256
num_labels: 2500 # 100 2500cifar100
batch_size: 64 # 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95 # 0.7 ou .95 pour fixmatchtau for pseudo labeling
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: True
clip: 0.0
net: resnet50
net_from_name: False # If True, net_builder takes models in torch.vision models (False de base)
data_dir: ./data
train_sampler: RandomSampler
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None




