# D cifar100 2500 labels

algorithm: fixmatch # fixmatch
save_dir: ./saved_models/
resume: True
load_path: auto
overwrite: True
use_tensorboard: True
use_wandb: True
epoch: 512  #256 #512 #1024
num_train_iter: 524288 # 262144 # 524288 # 1048576
num_eval_iter: 5120
num_log_iter: 5120 #256
num_labels: 2500
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001 #0.001 pour cifar100
layer_decay: 1.0
amp: True
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_workers: 1
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None

wandb_project: D
save_name: D2f




