# D stl10 250 laebls
algorithm: semisupconproto # fixmatch
save_dir: ./saved_models/classic_cv
resume: True
load_path: auto
overwrite: True
use_tensorboard: True
use_wandb: True
epoch: 512  #256 #512 #1024
num_train_iter: 524288 # 262144 # 524288 # 1048576
num_eval_iter: 5120
num_log_iter: 5120 #256
num_labels: 250
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 96
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005 #0.001 pour cifar100
layer_decay: 1.0
amp: True
clip: 0.0
use_cat: True
net: wrn_var_37_2_proto
net_from_name: False
data_dir: ./data
dataset: stl10
train_sampler: RandomSampler
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None

wandb_project: semisupcon_datasets
save_name: D6
loss: OnlySupconWeightsOnUnconfident # Supcon&Simclr #OnlySupcon                        #all_withoutsimclr #all_withoutsimclr_withoutunsupce # all #only_unsup (for pretraining, and resume = True)
lambda_proto: 0.2 #only for Weighted supcon loss
pl: softmax # softmax
pl_temp: .04


