algorithm: semisupcon
loss: only_unsup # all
save_dir: ./saved_models/pretrained
save_name: semisupcon(pretrained) #(without simclr)
resume: True
resume_only_weight: True # When resuming a model, only take the weight for finetuning (make epochs,scheduler, optimizer start from scratch)
load_path: ./pretrained/pretrainedSimCLRcifar100wrn_28_2_epochs256/epoch124.pth
overwrite: True
use_tensorboard: True
use_wandb: True
epoch: 256
num_train_iter: 262144
num_eval_iter: 5120
num_log_iter: 256
num_labels: 100 #2500
batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False # If True, net_buidler takes models in torch.vision models.
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None

